version: "3"

services:

  minio-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MINIO_ENDPOINT=minio-store:9000
      - MINIO_ACCESS_KEY_ID=minio
      - MINIO_SECRET_ACCESS_KEY=minio123
      - MINIO_SECURE=false
      - MINIO_DEFAULT_HTML=index.html
      - MINIO_FAVICON=assets/favicon.ico
      - MINIO_MD_TEMPLATE=assets/md-template.html
    depends_on:
      - minio-store

  minio-store:
    image: minio/minio
    ports:
      - 9000:9000
    expose:
      - 9000
    volumes:
      - ./tmp:/daya
    command:
      - server
      - /data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
