apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-web
  labels:
    app: minio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-web
  template:
    metadata:
      labels:
        app: minio-web
    spec:
      containers:
      - name: minio-web
        image: e2fyi/minio-web:latest
        env:
          - name: AWS_METADATA_SERVICE_TIMEOUT
            value: "10"
          - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
            value: "20"
          - name: MINIO_ENDPOINT
            value: s3.amazonaws.com
          - name: MINIO_SECURE
            value: "true"
          - name: MINIO_ACCESSKEY
            value: ""
          - name: MINIO_SECRETKEY
            value: ""
          - name: MINIO_REGION
            value: ap-southeast-1
          - name: EXT_BUCKETNAME
            value: ""
          - name: EXT_PREFIX
            value: ""
          - name: EXT_DEFAULTHTML
            value: index.html
          - name: EXT_FAVICON
            value: assets/favicon.ico
          - name: EXT_MARKDOWNTEMPLATE
            value: assets/md-template.html
          - name: EXT_LISTFOLDER
            value: "true"
          - name: EXT_LISTFOLDEROBJECTS
            value: "*.md"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "100m"
          limits:
            memory: "8Gi"
            cpu: "1000m"