
apiVersion: v1
kind: Service
metadata:
  name: minio-web
  labels:
    app: minio-web
spec:
  type: ClusterIP
  selector:
    app: minio-web
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 8080
